spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testNew
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.xml

server:
  port: 8081